baseurl: /simvent.js
defaults:
 -
  scope:
   path: ""
   type: "pages"
  values:
   layout: "page"
 -
  scope:
   path: ""
   type: "posts"
  values:
   layout: "post"
exclude: ["test", "lib", "out", "node_modules"]
