defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
gems: ['jekyll-paginate']
plugins:
  - jekyll-paginate
plugins-dir:
  - jekyll-paginate
paginate: 6
